services:
  - type: web
    name: instalaciones
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn instalaciones.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "pon-una-clave-segura-aqui"
      - key: DEBUG
        value: "0"
