# Generated by Django 5.1.6 on 2025-04-19 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cuadroInst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvg', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('codigo', models.IntegerField(default=0)),
                ('cliente', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('tecnico1', models.IntegerField(choices=[(1, 'Ricardo'), (2, 'Giovanny'), (3, 'Juan'), (4, 'Francisco'), (5, 'German'), (6, 'Willinthon'), (7, 'Jhon'), (8, 'Guido'), (9, 'Esneyder'), (10, 'Diego')], default=1)),
                ('tecnico2', models.IntegerField(choices=[(1, 'Ricardo'), (2, 'Giovanny'), (3, 'Juan'), (4, 'Francisco'), (5, 'German'), (6, 'Willinthon'), (7, 'Jhon'), (8, 'Guido'), (9, 'Esneyder'), (10, 'Diego')], default=1)),
                ('ejecutivo', models.IntegerField(choices=[(1, 'Francisco Silva'), (2, 'Andrea Trujillo'), (3, 'Yamile David')], default=1)),
                ('finalizacion', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
