# Generated by Django 4.2.11 on 2024-04-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuadroInst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvg', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField()),
                ('codigo', models.IntegerField(default=0)),
                ('cliente', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=100)),
                ('tecnicos', models.CharField(choices=[('seleccione', '...'), ('tecnico A', 'Tecnico A'), ('tecnico B', 'Tecnico B'), ('tecnico C', 'Tecnico C')], default='seleccione', max_length=20)),
                ('ejecutivo', models.CharField(max_length=20)),
                ('finalizacion', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
