# Generated by Django 5.1.6 on 2025-08-19 12:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejecutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('novedad', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('codigo', models.IntegerField()),
                ('tecnico', models.CharField(max_length=50)),
                ('pendiente', models.TextField(blank=True, null=True)),
                ('horas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('orden', models.CharField(blank=True, max_length=50, null=True)),
                ('realizado', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, unique=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuadroInsta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pvg', models.IntegerField(blank=True, db_index=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('instalacion', models.TextField(blank=True, null=True)),
                ('dias_cotizados', models.IntegerField(blank=True, null=True)),
                ('cantidad_tecnicos', models.IntegerField(blank=True, null=True)),
                ('en_bodega', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_terminacion', models.DateField(blank=True, null=True)),
                ('finaliza', models.DateField(blank=True, null=True)),
                ('orden', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ejecutivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_instalaciones.ejecutivo')),
                ('tecnico1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadroinsta_tecnico1', to='app_instalaciones.tecnico')),
                ('tecnico2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadroinsta_tecnico2', to='app_instalaciones.tecnico')),
            ],
            options={
                'ordering': ['-fecha', '-updated_at'],
                'unique_together': {('pvg', 'ciudad')},
            },
        ),
    ]
