# Generated by Django 4.2.19 on 2025-12-16 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='mantenimientos/'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_falla',
            field=models.CharField(blank=True, choices=[('F.COMUNICACION', 'F.Comunicación'), ('F.CORRIENTE', 'F.Corriente'), ('ACTIVACION', 'Activación'), ('PROGRAMACION', 'Programación'), ('ACT.DATOS', 'Act.datos'), ('OTRO SERVICIO', 'Otro servicio'), ('CCTV', 'CCTV'), ('INSTALACION', 'Instalación'), ('MANTO PREVENTIVO', 'Manto preventivo'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_instalaciones.tecnico'),
        ),
    ]
