# Generated by Django 5.1.6 on 2025-08-19 00:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuadroinsta',
            options={'ordering': ['-fecha', '-updated_at']},
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='ciudad',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='en_bodega',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='pvg',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cuadroinsta',
            unique_together={('pvg', 'ciudad')},
        ),
    ]
