# Generated by Django 4.2.19 on 2025-11-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_falla',
            field=models.CharField(blank=True, choices=[('FALLA1', 'Falla 1'), ('FALLA2', 'Falla 2'), ('FALLA3', 'Falla 3'), ('OTRA', 'Otra')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_instalaciones.tecnico'),
        ),
    ]
