# Generated by Django 4.2.19 on 2025-11-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0002_mantenimiento_tipo_falla_alter_mantenimiento_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo_falla',
            field=models.CharField(blank=True, choices=[('F.COMUNICACION', 'F.Comunicación'), ('F.CORRIENTE', 'F.Corriente'), ('ACTIVACION', 'Activación'), ('PROGRAMACION', 'Programación'), ('ACT.DATOS', 'Act.datos'), ('OTRO SERVICIO', 'Otro servicio'), ('CCTV', 'CCTV'), ('INSTALACION', 'Instalación'), ('MANTO PREVENTIVO', 'Manto preventivo'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
    ]
