# Generated by Django 4.2.11 on 2024-04-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0002_remove_cuadroinst_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadroinst',
            name='tecnicos',
            field=models.CharField(max_length=50),
        ),
    ]
