# Generated by Django 4.2.19 on 2025-04-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0002_rename_cuadroinst_cuadroinsta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadroinsta',
            name='cantidad_tecnicos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuadroinsta',
            name='dias_cotizados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuadroinsta',
            name='en_bodega',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='SI', max_length=3),
        ),
        migrations.AddField(
            model_name='cuadroinsta',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuadroinsta',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuadroinsta',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuadroinsta',
            name='finaliza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cuadroinsta',
            name='instalacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuadroinsta',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuadroinsta',
            name='orden',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='ejecutivo',
            field=models.IntegerField(choices=[(1, 'Francisco Silva'), (2, 'Andrea Trujillo'), (3, 'Yamile David'), (4, '-----')], default=1),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='tecnico1',
            field=models.IntegerField(choices=[(1, 'Ricardo'), (2, 'Giovanny'), (3, 'Juan'), (4, 'Francisco'), (5, 'German'), (6, 'Willinthon'), (7, 'Jhon'), (8, 'Guido'), (9, 'Esneyder'), (10, 'Diego'), (11, '-----')], default=1),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='tecnico2',
            field=models.IntegerField(choices=[(1, 'Ricardo'), (2, 'Giovanny'), (3, 'Juan'), (4, 'Francisco'), (5, 'German'), (6, 'Willinthon'), (7, 'Jhon'), (8, 'Guido'), (9, 'Esneyder'), (10, 'Diego'), (11, '-----')], default=1),
        ),
    ]
