# Generated by Django 4.2.19 on 2025-04-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0003_cuadroinsta_cantidad_tecnicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadroinsta',
            name='en_bodega',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2),
        ),
    ]
