# Generated by Django 4.2.19 on 2025-11-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0003_alter_mantenimiento_tipo_falla'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='mantenimientos/'),
        ),
    ]
