# Generated by Django 4.2.19 on 2025-04-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0004_alter_cuadroinsta_en_bodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadroinsta',
            name='finaliza',
            field=models.DateField(blank=True, null=True),
        ),
    ]
