# Generated by Django 4.2.19 on 2026-06-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0006_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadroinsta',
            name='alistado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuadroinsta',
            name='fecha_alistado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
