# Generated by Django 4.2.19 on 2025-05-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0006_registroimportacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadroinsta',
            name='ciudad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='ejecutivo',
            field=models.IntegerField(choices=[(1, 'Francisco Silva'), (2, 'Andrea Trujillo'), (3, 'Yamile David'), (4, '-----')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='en_bodega',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], default='NO', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='tecnico1',
            field=models.IntegerField(choices=[(1, 'Ricardo'), (2, 'Giovanny'), (3, 'Juan'), (4, 'Francisco'), (5, 'German'), (6, 'Willinthon'), (7, 'Jhon'), (8, 'Guido'), (9, 'Esneyder'), (10, 'Diego'), (11, '-----')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='cuadroinsta',
            name='tecnico2',
            field=models.IntegerField(choices=[(1, 'Ricardo'), (2, 'Giovanny'), (3, 'Juan'), (4, 'Francisco'), (5, 'German'), (6, 'Willinthon'), (7, 'Jhon'), (8, 'Guido'), (9, 'Esneyder'), (10, 'Diego'), (11, '-----')], default=1, null=True),
        ),
    ]
