# Generated by Django 4.2.19 on 2026-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0007_cuadroinsta_alistado_cuadroinsta_fecha_alistado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo_servicio',
            field=models.CharField(choices=[('MANTENIMIENTO CORRECTIVO', 'Mantenimiento correctivo'), ('MANTENIMIENTO PREVENTIVO', 'Mantenimiento preventivo'), ('INSTALACION', 'Instalación'), ('CCTV', 'CCTV'), ('OTRO SERVICIO', 'Otro servicio')], db_index=True, default='MANTENIMIENTO CORRECTIVO', max_length=30),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo_falla',
            field=models.CharField(blank=True, choices=[('F.COMUNICACION', 'F.Comunicación'), ('F.CORRIENTE', 'F.Corriente'), ('ACTIVACION', 'Activación'), ('PROGRAMACION', 'Programación'), ('ACT.DATOS', 'Act.datos'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
    ]
