# Generated by Django 4.2.19 on 2026-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0008_mantenimiento_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
