# Generated by Django 4.2.19 on 2026-07-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0009_alter_mantenimiento_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='codigo_acta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='cotizacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_orden',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='numero_orden',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='omt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='problema_solucionado',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
