# Generated by Django 4.2.19 on 2026-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0010_mantenimiento_codigo_acta_mantenimiento_cotizacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='numero_orden',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='numero_ticket',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Ticket'),
        ),
    ]
