# Generated by Django 4.2.19 on 2026-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0011_remove_mantenimiento_numero_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='estado_orden',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_ticket',
            field=models.CharField(
                blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
