# Generated by Django 5.2.13 on 2026-07-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0012_remove_mantenimiento_estado_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo_falla',
            field=models.CharField(blank=True, choices=[('F.COMUNICACION', 'F. Comunicación'), ('F.CORRIENTE', 'F. Corriente'), ('FALLOS EQUIPOS', 'Fallos equipos'), ('ACTIVACION', 'Activación'), ('PROGRAMACION', 'Programación'), ('ACT.DATOS', 'Actualización de datos'), ('CCTV', 'CCTV'), ('INSTALACION', 'Instalación'), ('MANTO PREVENTIVO', 'Mantenimiento preventivo'), ('OTRO SERVICIO', 'Otro servicio'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
    ]
