# Generated by Django 5.2.13 on 2026-07-17 14:58

from django.db import migrations, models


def migrar_facturados_existentes(apps, schema_editor):
    CuadroInsta = apps.get_model('app_instalaciones', 'CuadroInsta')
    CuadroInsta.objects.filter(facturado=True).update(
        estado_facturacion='FACTURADO'
    )


def restaurar_booleano_facturado(apps, schema_editor):
    CuadroInsta = apps.get_model('app_instalaciones', 'CuadroInsta')
    CuadroInsta.objects.filter(estado_facturacion='FACTURADO').update(
        facturado=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0013_alter_mantenimiento_tipo_falla'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadroinsta',
            name='estado_facturacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FACTURADO', 'Facturado'), ('RETENIDO', 'Retenido')], db_index=True, default='PENDIENTE', max_length=10),
        ),
        migrations.RunPython(
            migrar_facturados_existentes,
            restaurar_booleano_facturado,
        ),
    ]
