# Generated by Django 5.2.13 on 2026-07-18 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0014_cuadroinsta_estado_facturacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_operativo',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_programada',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='Usuario que ingresará al portal móvil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistorialAsignacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_asignaciones', to='app_instalaciones.mantenimiento')),
                ('tecnico_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_retiradas', to='app_instalaciones.tecnico')),
                ('tecnico_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_recibidas', to='app_instalaciones.tecnico')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ASIGNACION', 'Asignación'), ('REASIGNACION', 'Reasignación'), ('RETIRADO', 'Servicio retirado')], max_length=20)),
                ('mensaje', models.CharField(max_length=250)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app_instalaciones.mantenimiento')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app_instalaciones.tecnico')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
