# Generated by Django 5.2.13 on 2026-07-22 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0015_mantenimiento_estado_operativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_orden',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
