# Generated by Django 5.2.13 on 2026-07-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0016_mantenimiento_fecha_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fin_tecnico',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='inicio_tecnico',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
