# Generated by Django 5.2.13 on 2026-07-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0017_mantenimiento_fin_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha_creacion_servicio',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
