# Generated by Django 5.2.13 on 2026-07-31 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0021_rename_smartcheck_verbose_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitProyectoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProyectoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PANEL', 'Panel de alarma'), ('SENSOR', 'Sensor o dispositivo de zona'), ('MODULO', 'Módulo'), ('EQUIPO', 'Equipo adicional'), ('ACCESORIO', 'Accesorio')], db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tipo_cable', models.CharField(blank=True, choices=[('', 'No aplica / definir en campo'), ('2X22', 'Cable 2x22'), ('4X22', 'Cable 4x22'), ('UTP', 'Cable UTP')], max_length=10)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categoria', 'nombre', 'referencia'],
            },
        ),
        migrations.CreateModel(
            name='ItemKitProyectoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_instalaciones.kitproyectocomercial')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_instalaciones.productoproyectocomercial')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kit', 'producto'), name='producto_unico_por_kit_comercial')],
            },
        ),
    ]
