# Generated by Django 5.2.13 on 2026-07-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0022_kitproyectocomercial_productoproyectocomercial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoproyectocomercial',
            name='tipo_cable',
        ),
        migrations.AddField(
            model_name='productoproyectocomercial',
            name='unidad',
            field=models.CharField(default='Unidad', max_length=30),
        ),
        migrations.AlterField(
            model_name='productoproyectocomercial',
            name='categoria',
            field=models.CharField(choices=[('PANEL', 'Panel de alarma'), ('SENSOR', 'Sensor o dispositivo de zona'), ('MODULO', 'Módulo'), ('EQUIPO', 'Equipo adicional'), ('CABLE', 'Cable'), ('ACCESORIO', 'Accesorio')], db_index=True, max_length=20),
        ),
    ]
