# Generated by Django 5.2.13 on 2026-07-31 15:19

from django.db import migrations, models


def normalizar_estados(apps, schema_editor):
    Proyecto = apps.get_model('app_instalaciones', 'ProyectoSmartCheck')
    equivalencias = {
        'BORRADOR': 'VISITA_PROGRAMADA',
        'LEVANTAMIENTO': 'VISITA_PROGRAMADA',
        'DISENO': 'PROPUESTA_DISENO',
        'PROPUESTA': 'PROPUESTA_DISENO',
        'REVISION_CLIENTE': 'ENVIADA',
        'INSTALACION': 'APROBADA',
        'PRUEBAS': 'APROBADA',
        'ENTREGA': 'APROBADA',
        'ENTREGADA': 'CERRADA',
    }
    for anterior, nuevo in equivalencias.items():
        Proyecto.objects.filter(estado=anterior).update(estado=nuevo)


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0023_remove_productoproyectocomercial_tipo_cable_and_more'),
    ]

    operations = [
        migrations.RunPython(normalizar_estados, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='proyectosmartcheck',
            name='estado',
            field=models.CharField(choices=[('VISITA_PROGRAMADA', 'Visita programada'), ('PROPUESTA_DISENO', 'Propuesta de diseño'), ('ENVIADA', 'Propuesta enviada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CERRADA', 'Cerrada')], db_index=True, default='VISITA_PROGRAMADA', max_length=30),
        ),
    ]
