# Generated by Django 5.2.13 on 2026-07-31 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0024_alter_proyectosmartcheck_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionProyectoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propuesta', models.CharField(blank=True, max_length=160)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_instalaciones.kitproyectocomercial')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion', to='app_instalaciones.proyectosmartcheck')),
            ],
            options={
                'verbose_name': 'Cotización de proyecto comercial',
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacionProyectoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('incluido_kit', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app_instalaciones.cotizacionproyectocomercial')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_instalaciones.productoproyectocomercial')),
            ],
            options={
                'ordering': ['orden', 'pk'],
            },
        ),
    ]
