# Generated by Django 5.2.13 on 2026-08-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0025_cotizacionproyectocomercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitproyectocomercial',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
