# Generated by Django 5.2.13 on 2026-08-03 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0027_normalizar_textos_comerciales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Agregó'), ('EDITAR', 'Editó'), ('ELIMINAR', 'Eliminó')], db_index=True, max_length=12)),
                ('modulo', models.CharField(db_index=True, max_length=100)),
                ('modelo', models.CharField(db_index=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('objeto', models.CharField(blank=True, max_length=300)),
                ('cambios', models.JSONField(blank=True, default=dict)),
                ('ruta', models.CharField(blank=True, max_length=300)),
                ('metodo', models.CharField(blank=True, max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_aplicacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de movimiento',
                'verbose_name_plural': 'Registro de movimientos',
                'ordering': ['-fecha', '-pk'],
            },
        ),
    ]
