# Generated by Django 5.2.13 on 2026-08-04 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0028_registroauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaNoLaboralTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='JornadaLaboralTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BASE', 'Horario base'), ('DISPONIBLE', 'Técnico disponible')], default='BASE', max_length=15)),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('entrada_1', models.TimeField(blank=True, null=True)),
                ('salida_1', models.TimeField(blank=True, null=True)),
                ('entrada_2', models.TimeField(blank=True, null=True)),
                ('salida_2', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo', 'dia_semana'],
                'constraints': [models.UniqueConstraint(fields=('tipo', 'dia_semana'), name='jornada_tecnica_tipo_dia_unica')],
            },
        ),
        migrations.CreateModel(
            name='RotacionTecnicoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Se almacena como el primer día del mes.', unique=True)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotaciones_disponible', to='app_instalaciones.tecnico')),
            ],
            options={
                'ordering': ['-mes'],
            },
        ),
    ]
