# Generated by Django 5.2.13 on 2026-08-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0030_rotacion_disponible_por_sabado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='incluir_indicadores',
            field=models.BooleanField(default=True, help_text='Incluye al técnico en los indicadores de atención y ocupación.'),
        ),
    ]
