# Generated by Django 5.2.13 on 2026-09-09 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0031_tecnico_incluir_indicadores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaComercialFonel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(db_index=True, max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('ciudad', models.CharField(blank=True, db_index=True, max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=180)),
                ('fecha_visita', models.DateField(db_index=True)),
                ('tipo_oportunidad', models.CharField(choices=[('ALARMA', 'Sistema de alarma'), ('CCTV', 'Videovigilancia'), ('ACCESO', 'Control de acceso'), ('INTELIGENTE', 'Edificio inteligente'), ('OTRO', 'Otro')], default='ALARMA', max_length=20)),
                ('etapa', models.CharField(choices=[('PROSPECTO', 'Prospecto'), ('CONTACTADO', 'Contactado'), ('VISITA_PROGRAMADA', 'Visita programada'), ('VISITA_REALIZADA', 'Visita realizada'), ('PROPUESTA', 'Propuesta en preparación'), ('NEGOCIACION', 'Negociación'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida')], db_index=True, default='VISITA_PROGRAMADA', max_length=30)),
                ('necesidad', models.TextField(blank=True)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('probabilidad', models.PositiveSmallIntegerField(default=10)),
                ('proxima_gestion', models.DateField(blank=True, db_index=True, null=True)),
                ('compromiso', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True, db_index=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_comerciales_fonel_creadas', to=settings.AUTH_USER_MODEL)),
                ('ejecutivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_comerciales_fonel', to='app_instalaciones.ejecutivo')),
            ],
            options={
                'verbose_name': 'Visita comercial Fonel',
                'verbose_name_plural': 'Visitas comerciales Fonel',
                'ordering': ['-fecha_visita', '-pk'],
            },
        ),
    ]
