# Generated by Django 5.2.13 on 2026-09-09 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_instalaciones', '0032_visita_comercial_fonel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitacomercialfonel',
            name='fecha_forecast',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='visitacomercialfonel',
            name='pasado_forecast_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_comerciales_pasadas_forecast', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitacomercialfonel',
            name='etapa',
            field=models.CharField(choices=[('PROSPECTO', 'Prospecto'), ('CONTACTADO', 'Contactado'), ('VISITA_PROGRAMADA', 'Visita programada'), ('VISITA_REALIZADA', 'Visita realizada'), ('PROPUESTA', 'Propuesta en preparación'), ('FORECAST', 'Forecast'), ('NEGOCIACION', 'Negociación'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida')], db_index=True, default='VISITA_PROGRAMADA', max_length=30),
        ),
    ]
