"""
Django settings for instalaciones project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url  # type: ignore

# === Entorno y rutas ===
AMBIENTE = os.getenv("AMBIENTE", "local").lower()  # "local" o "produccion"
BASE_DIR = Path(__file__).resolve().parent.parent

# === Clave secreta ===
SECRET_KEY = os.getenv("SECRET_KEY", "dev-secret-change-me")

# === Debug y hosts ===
DEBUG = AMBIENTE != "produccion"
ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] if DEBUG else os.getenv(
    "ALLOWED_HOSTS", "*").split(",")

# === Apps ===
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'app_instalaciones',
    'widget_tweaks',  # pip install django-widget-tweaks
]

# === Middleware ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise solo en prod (lo insertamos más abajo si aplica)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if AMBIENTE == "produccion":
    # agregar una sola vez y en el orden recomendado:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

# === URLs y WSGI ===
ROOT_URLCONF = 'instalaciones.urls'
WSGI_APPLICATION = 'instalaciones.wsgi.application'

# === Templates ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # más robusto que 'templates' a secas
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# === Base de datos ===
if AMBIENTE == "produccion":
    # Intenta usar dj-database-url si está disponible y hay DATABASE_URL
    try:
        import dj_database_url  # pip install dj-database-url
    except ModuleNotFoundError:
        dj_database_url = None

    if dj_database_url and os.getenv("DATABASE_URL"):
        DATABASES = {'default': dj_database_url.config(conn_max_age=600)}
    else:
        # Fallback seguro para no romper en un PC sin dependencias/vars
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# === Password validators ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === i18n ===
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# === Archivos estáticos y media ===
STATIC_URL = '/static/'
MEDIA_URL = '/media/'

if AMBIENTE == "produccion":
    STATIC_ROOT = BASE_DIR / 'staticfiles'
    # WhiteNoise en producción
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    STATICFILES_DIRS = [BASE_DIR / 'static']
    MEDIA_ROOT = BASE_DIR / 'media'

# === Login y sesiones ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'home'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

SESSION_COOKIE_AGE = 600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
